### ISSUE TITLE
Problems with instance operation

### ISSUE THREAD

**Issue by chenzhaoxingxin** [pvanberg/MATH0471-DG#4]
Dear author, by downloading the content you uploaded, I understand that you have studied the content of the intermittent Galerkin finite element in depth, and the information you uploaded has been of great help to my study. As a beginner, I express my gratitude to you again.
But when I run the example you gave, the results I get are a bit unintelligible.
./dgalerkin ../../doc/2d/square.msh ../../doc/config/config.conf 

The parameters in the config.conf file are as follows:
timeStart=0
timeEnd=0.1
timeStep=0.0001
timeRate=0.001
elementType=Lagrange
timeIntMethod=Runge-Kutta
Reflecting = Reflecting
Absorbing = Absorbing
MyPhysicalName = Absorbing
numThreads=4
v0_x = 0
v0_y = 0
v0_z = 0
rho0 = 1.225
c0 = 343.3
initialCondtition1 = gaussian, 0,0,0,1,1
saveFile=data.msh
（I see that in the config.conf file file, the Source command is commented out, and I have not changed this.）
Use the command   gmsh data.msh  to view the generated .msh file.
The results I got are shown in the figure below. I haven't seen the phenomenon of sound wave propagation in the picture. As a beginner, I don't understand it here. I hope you are busy to answer my doubts.
![~)GN2CXM64)RNM3Q{` 1{XG](https://user-images.githubusercontent.com/50125253/87129400-da979580-c2c3-11ea-90bc-61489cc619ce.png)

Thank you again for the information you have shared and your contribution in this research direction.

**Comment by povanberg** [comment]
Hello,

The simulation looks good. The picture show the first time frame, I.e. time step 0 in [0, 2000], see lower left corner of the picture. It displays the initial condition imposed in the config file, i.e. a gaussian centered in 0,0 with a width of 1:

`initialCondtition1 = gaussian, 0,0,0,1,1`

By default arrow keys left/right should display the next frames and the wave propagation.

**Comment by chenzhaoxingxin** [comment]
Thank you for your busy schedule and answering my question. I tried it according to the method you said and saw a good simulation effect.
![QQ图片20200711091829](https://user-images.githubusercontent.com/50125253/87213436-83430500-c357-11ea-9dc8-e1bffa15be4f.png)
thank you for your help!
Finally, I would like to ask you, the acoustic wave equation you are solving is of general form
![image](https://user-images.githubusercontent.com/50125253/87213559-7d99ef00-c358-11ea-8209-d5a0f955667c.png)

Or the first-order hyperbolic form of the acoustic wave equation
![image](https://user-images.githubusercontent.com/50125253/87213589-a326f880-c358-11ea-80cf-e2700973cddd.png)
?

**Comment by povanberg** [comment]
The simulations solve the linearized Euler equation (perturbation of the mean flow). All equations and derivation are summarized in the report (section 3):

[https://raw.githubusercontent.com/pvanberg/DGFEM-Acoustic/master/DGFEM_acoustic.pdf](https://github.com/pvanberg/DGFEM-Acoustic/blob/master/DGFEM_acoustic.pdf)

**Comment by chenzhaoxingxin** [comment]
Thank you for your help!
